import {Area,AreaChart,Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'
import {AppShell} from '../../app/AppShell'; import {activity,departments,evaluationDistribution,headcount,employees} from '../../mock/people-data'; import {Badge,Avatar,Progress} from '../../components/UI'
const tip={background:'#fff',border:'1px solid #e7e4f0',borderRadius:10}
export function DashboardPage(){return <AppShell title="Visão geral" subtitle="Acompanhe o quadro, desempenho e desenvolvimento da sua organização." actions={<button>+ Nova ação</button>}>
<div className="hero-grid"><div className="hero-card"><div><span className="overline">RESUMO DO MÊS · SETEMBRO 2026</span><h2>Olá, Mariana 👋</h2><p>Seu time está evoluindo bem. <b>3 pessoas</b> estão prontas para uma conversa de carreira.</p><button className="ghost">Ver recomendações →</button></div><div className="hero-score"><strong>82%</strong><span>engajamento</span><small>+4,2% no ciclo</small></div></div></div>
<section className="kpi-grid six"><div className="metric"><span>Colaboradores</span><strong>127</strong><small className="up">↑ 5 este mês</small></div><div className="metric"><span>Em avaliação</span><strong>94%</strong><small>23 pendentes</small></div><div className="metric"><span>PDIs ativos</span><strong>43</strong><small className="up">↑ 12 no ciclo</small></div><div className="metric"><span>Metas ativas</span><strong>86</strong><small>18 em risco</small></div><div className="metric"><span>Turnover</span><strong>1,8%</strong><small className="up">↓ 0,3pp</small></div><div className="metric"><span>Tempo de casa</span><strong>2,8</strong><small>anos em média</small></div></section>
<div className="dashboard-grid"><section className="section-card chart-wide"><div className="section-head"><div><h2>Evolução do quadro</h2><p>Colaboradores ativos nos últimos 6 meses</p></div><select><option>Últimos 6 meses</option></select></div><ResponsiveContainer width="100%" height={250}><AreaChart data={headcount}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopOpacity={.25}/><stop offset="100%" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#eeeaf6" vertical={false}/><XAxis dataKey="m" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip contentStyle={tip}/><Area type="monotone" dataKey="v" stroke="#6755e8" strokeWidth={3} fill="url(#fill)"/></AreaChart></ResponsiveContainer></section>
<section className="section-card"><div className="section-head"><div><h2>Avaliações do ciclo</h2><p>Distribuição das notas</p></div><button className="link-btn">Detalhes</button></div><div className="donut"><PieChart width={180} height={180}><Pie data={evaluationDistribution} dataKey="value" innerRadius={55} outerRadius={78} paddingAngle={3}>{evaluationDistribution.map((x,i)=><Cell key={x.label} fill={['#6755e8','#8b7ff0','#b7aff7','#e9e6fb'][i]}/>)}</Pie></PieChart><div>{evaluationDistribution.map(x=><div className="legend-row" key={x.label}><span className="legend-dot"/>{x.label}<b>{x.value}%</b></div>)}</div></div></section>
<section className="section-card"><div className="section-head"><div><h2>Colaboradores por setor</h2><p>Distribuição atual</p></div></div><ResponsiveContainer width="100%" height={250}><BarChart data={departments} layout="vertical" margin={{left:15,right:15}}><CartesianGrid stroke="#eeeaf6" horizontal={false}/><XAxis type="number" axisLine={false} tickLine={false}/><YAxis type="category" dataKey="name" width={105} axisLine={false} tickLine={false} fontSize={12}/><Tooltip contentStyle={tip}/><Bar dataKey="people" fill="#6755e8" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></section>
<section className="section-card"><div className="section-head"><div><h2>Atividade recente</h2><p>Últimas ações no People OS</p></div><button className="link-btn">Ver tudo</button></div><div className="activity-list">{activity.map((a,i)=><div className="activity" key={i}><Avatar initials={a.who==='Sistema'?'IA':a.who.split(' ').map(x=>x[0]).join('').slice(0,2)}/><div><b>{a.who}</b> <span>{a.text}</span><small>{a.time}</small></div></div>)}</div></section></div>
<section className="section-card"><div className="section-head"><div><h2>Radar de pessoas</h2><p>Quem merece atenção nesta semana</p></div><button className="link-btn">Abrir análise</button></div><div className="radar-grid">{employees.slice(0,4).map(e=><div className="person-row" key={e.id}><Avatar initials={e.initials}/><div><b>{e.name}</b><small>{e.role}</small></div><div className="person-stat"><span>Desempenho</span><strong>{e.performance.toFixed(1)}</strong></div><div className="person-stat"><span>PDI</span><Progress value={e.pdi}/></div><Badge tone={e.performance>=4.5?'success':e.engagement<80?'warning':'info'}>{e.performance>=4.5?'Alta prontidão':e.engagement<80?'Atenção':'Em evolução'}</Badge></div>)}</div></section>
</AppShell>}
