import { useState } from 'react'
import { Shell } from '../components/Shell'
import { Icon } from '../components/Icon'
import { alerts, shelters, type PageKey } from '../data/mock'

const Pill=({children,tone='green'}:{children:React.ReactNode;tone?:string})=><span className={`status-pill ${tone}`}>{children}</span>
const Title=({title,action,onAction}:{title:string;action?:string;onAction?:()=>void})=><div className="section-title"><h1>{title}</h1>{action&&<button className="text-action" onClick={onAction}>{action} ›</button>}</div>

function Home({go}:{go:(p:PageKey)=>void}){return <div className="stack">
<div className="hero-alert"><div className="hero-top"><div className="risk-number">3</div><div><span className="hero-label">NÍVEL DE RISCO</span><h2>Alerta</h2></div><Icon name="rain" size={46} className="hero-rain"/></div><p>Chuva forte pode causar alagamentos nas próximas horas.</p><div className="hero-advice"><Icon name="alert" size={16}/><span><small>O que fazer agora</small><strong>Evite áreas baixas e prepare seu deslocamento.</strong></span></div><button className="hero-button" onClick={()=>go('notificacoes')}>Ver alerta completo ›</button></div>
<Title title="Ações rápidas" action="Priorize sua segurança"/><div className="quick-grid"><Quick icon="map" title="Mapa de risco" sub="Veja áreas afetadas" go={()=>go('mapa')}/><Quick icon="shelter" title="Encontrar abrigo" sub="3 locais próximos" go={()=>go('abrigos')}/><Quick icon="checklist" title="Meu plano" sub="62% preparado" go={()=>go('plano')}/><Quick icon="alert" title="Relatar ocorrência" sub="Ajude sua comunidade" go={()=>go('notificacoes')}/></div>
<Title title="Locais importantes" action="Ver todos" onAction={()=>go('mapa')}/><div className="locations-card"><Loc t="Minha casa" s="Menino Deus" c="red" st="Alerta"/><Loc t="Casa da mãe" s="Cidade Baixa" c="orange" st="Atenção"/><Loc t="Trabalho" s="Moinhos de Vento" c="green" st="Normal"/></div>
<div className="river-card" onClick={()=>go('clima')}><div className="river-icon"><Icon name="rain" size={22}/></div><div className="river-main"><span>Nível do Guaíba</span><strong>1,84 m</strong><small>Estação Usina do Gasômetro</small></div><b className="river-state">Subindo</b><div className="river-bar"><i/></div><small>Atualizado às 18:30 · Fonte: ANA/SGB</small></div><div className="emergency-note"><Icon name="shield" size={16}/> Em emergência, ligue para a Defesa Civil. Cadastre seu CEP pelo SMS 40199.</div></div>}
function Quick({icon,title,sub,go}:{icon:string;title:string;sub:string;go:()=>void}){return <button className="quick-card" onClick={go}><div className="quick-icon"><Icon name={icon}/></div><div><strong>{title}</strong><span>{sub}</span></div><i className="chevron">›</i></button>}
function Loc({t,s,c,st}:{t:string;s:string;c:string;st:string}){return <div className="location-row"><i className={`dot ${c}`}/><div><strong>{t}</strong><span>{s}</span></div><Pill tone={c}>{st}</Pill><i className="chevron">›</i></div>}

function MapPage({go}:{go:(p:PageKey)=>void}){return <div className="stack"><Title title="Mapa de risco" action="Filtros"/><div className="map-tabs"><button className="selected">Risco⌄</button><button>Abrigos</button><button>Bloqueios</button><button>Relatos</button></div><div className="map-card"><div className="fake-map"><div className="map-water"/><div className="map-road r1"/><div className="map-road r2"/><div className="map-road r3"/><span className="district d1">NAVEGANTES</span><span className="district d2">SANTANA</span><span className="district d3">MENINO DEUS</span><div className="risk-zone z1"/><div className="risk-zone z2"/><div className="map-pin home"><Icon name="home" size={15}/></div><div className="map-pin red"><Icon name="alert" size={14}/></div><div className="map-pin blue"/></div><div className="map-info"><div><Icon name="location"/><span><strong>Sua localização</strong><small>Menino Deus, Porto Alegre</small></span></div><span className="precision">Precisão alta ▮</span></div><div className="risk-summary"><div><Icon name="alert"/><span><strong>Risco alto nas próximas 6h</strong><small>Chuva forte e elevação do nível do Guaíba podem causar alagamentos.</small></span></div><button onClick={()=>go('abrigos')}>Ver rota segura ›</button></div></div></div>}
function Shelters(){return <div className="stack"><Title title="Abrigos próximos" action="Filtros"/><div className="filter-row"><button className="selected">Abertos</button><button>Com vagas</button><button>Acessíveis</button><button>Aceita animais</button></div><div className="list-stack">{shelters.map((s,i)=><div className="shelter-card" key={s.name}><div className={`shelter-icon ${i===2?'warn':''}`}><Icon name="shelter"/></div><div className="shelter-main"><strong>{s.name}</strong><span>{s.distance} · {s.time} · <b>{s.status}</b></span><small>Última confirmação há {i===0?'35':i===1?'50':'1h 10'} min</small><div className="shelter-tags"><span>♿ Acessível</span><span>🐾 Aceita animais</span></div></div><Pill tone={i===2?'orange':'green'}>{s.vacancies}</Pill><button className="card-arrow">›</button></div>)}</div><div className="route-card"><div><Icon name="route"/><span><small>Rota segura recomendada</small><strong>1,8 km · 8 min</strong></span></div><button>Ver rota segura</button></div></div>}
function Plan(){return <div className="stack"><Title title="Meu plano de emergência" action="Editar"/><div className="progress-card"><div><span>Preparação atual</span><strong>62%</strong></div><div className="progress"><i style={{width:'62%'}}/></div><small>Você está avançando. Complete os próximos itens para ficar mais preparado.</small></div><div className="plan-grid">{['Mochila de emergência','Contatos de emergência','Ponto de encontro familiar','Documentos importantes','Rotas seguras','Medicamentos e necessidades'].map((x,i)=><div className={`plan-item ${i<3?'done':''}`} key={x}><div className="check">{i<3?'✓':''}</div><span><strong>{x}</strong><small>{i<3?'Concluído':'Pendente'}</small></span><span>›</span></div>)}</div></div>}
function Notifications(){return <div className="stack"><Title title="Notificações" action="⚙"/><div className="filter-row"><button className="selected">Todas</button><button>Alertas</button><button>Atualizações</button></div><div className="notification-groups"><h3>Agora</h3>{alerts.map(a=><div className="notification" key={a.title}><div className={`notification-icon ${a.color}`}><Icon name={a.color==='green'?'shield':'alert'} size={17}/></div><div><strong>{a.title}</strong><span>{a.text}</span><small><Icon name="location" size={11}/> {a.place}</small></div><time>{a.time}</time><i className="unread"/></div>)}</div></div>}
function Weather(){return <div className="stack"><Title title="Clima e rios" action="Atualizar"/><div className="weather-main"><div><span>Porto Alegre · agora</span><strong>21°</strong><p>Chuva fraca · sensação 20°</p></div><Icon name="rain" size={55}/></div><div className="forecast-grid">{['Agora','14h','16h','18h','20h'].map((h,i)=><div key={h}><span>{h}</span><Icon name={i===0||i>2?'rain':'cloud'} size={22}/><strong>{21-Math.max(0,i-1)}°</strong><small>{i<2?'70%':'55%'}</small></div>)}</div><div className="river-detail"><div className="river-heading"><span>Nível do Guaíba</span><Pill tone="orange">Subindo</Pill></div><strong>1,84 m</strong><div className="river-line"><i/></div><div className="river-scale"><span>Normal</span><span>Cota de alerta 2,60 m</span></div><small>Estação Usina do Gasômetro · atualizado há 15 min</small></div></div>}
function Reports(){return <div className="stack"><Title title="Relatórios e indicadores" action="Exportar dados"/><div className="kpi-grid">{[['Alertas emitidos','1.248','+18,6%'],['Tempo médio de resposta','18m 42s','-5,1%'],['Unidades afetadas','53','+8,7%'],['Rotas planejadas','312','+22,1%']].map(x=><div className="kpi" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]} vs. período anterior</small></div>)}</div><div className="report-grid"><div className="panel"><h3>Alertas emitidos ao longo do período</h3><div className="chart"><div className="chart-line"/><div className="chart-axis"><span>01/mai</span><span>08/mai</span><span>15/mai</span><span>22/mai</span><span>31/mai</span></div></div></div><div className="panel"><h3>Distribuição por nível de risco</h3><div className="donut"><div><strong>1.248</strong><small>alertas</small></div></div><div className="legend"><span>● Crítico 16%</span><span>● Alto 32%</span><span>● Médio 29%</span><span>● Baixo 23%</span></div></div></div></div>}
function Profile(){return <div className="stack"><Title title="Perfil e conta" action="Editar"/><div className="profile-card"><div className="profile-avatar">AM</div><div><h2>Ana Demo</h2><span>Usuária · Menino Deus, Porto Alegre</span><small>Conta demonstrativa</small></div></div><div className="settings-list"><Setting icon="location" t="Região e locais salvos" v="3 locais"/><Setting icon="bell" t="Notificações" v="Ativas"/><Setting icon="shield" t="Privacidade e segurança" v="Gerenciar"/><Setting icon="settings" t="Acessibilidade" v="Configurar"/></div></div>}
function Setting({icon,t,v}:{icon:string;t:string;v:string}){return <button className="setting-row"><div className="setting-icon"><Icon name={icon}/></div><span><strong>{t}</strong><small>{v}</small></span><span>›</span></button>}
function Config(){return <div className="stack"><Title title="Configurações"/><div className="config-section"><h3>Organização e dados</h3><Setting icon="shield" t="Dados da organização" v="Ambiente demonstrativo"/><Setting icon="chart" t="Auditoria e suporte" v="Atividade, chamados e logs"/><Setting icon="settings" t="Plano e cobrança" v="Plano operacional"/></div><div className="config-section"><h3>Experiência</h3><Setting icon="bell" t="Preferências de alerta" v="Push, e-mail e SMS"/><Setting icon="info" t="Ajuda e fontes de dados" v="Saiba como os dados são usados"/></div></div>}

export default function App(){const [page,setPage]=useState<PageKey>('inicio');const pages:Record<PageKey,React.ReactNode>={inicio:<Home go={setPage}/>,mapa:<MapPage go={setPage}/>,abrigos:<Shelters/>,plano:<Plan/>,notificacoes:<Notifications/>,clima:<Weather/>,relatorios:<Reports/>,perfil:<Profile/>,configuracoes:<Config/>};return <Shell page={page} onNavigate={setPage}>{pages[page]}</Shell>}
