import {useMemo,useState} from 'react'; import {Link} from 'react-router-dom'; import {AppShell} from '../../app/AppShell'; import {Avatar,Badge,Modal,Progress} from '../../components/UI'; import {employees as seed,Employee} from '../../mock/people-data'
const tone=(s:string)=>s==='Ativo'?'success':s==='Férias'?'info':'neutral'
export function EmployeesPage(){const[data,setData]=useState(seed);const[q,setQ]=useState('');const[dept,setDept]=useState('Todos');const[status,setStatus]=useState('Todos');const[modal,setModal]=useState<'new'|'filter'|'import'|null>(null);const[view,setView]=useState<'table'|'cards'>('table');const filtered=useMemo(()=>data.filter(e=>(!q||`${e.name} ${e.role} ${e.email}`.toLowerCase().includes(q.toLowerCase()))&&(dept==='Todos'||e.department===dept)&&(status==='Todos'||e.status===status)),[data,q,dept,status]);
function add(){const n:Employee={id:`new-${Date.now()}`,name:'Novo Colaborador',initials:'NC',role:'Analista de Pessoas',department:'Recursos Humanos',manager:'Fernanda Oliveira',email:'novo.colaborador@empresa.com',status:'Ativo',contract:'CLT',level:'Júnior · Nível 1',admission:'04/09/2026',location:'Porto Alegre',performance:0,engagement:0,goals:0,pdi:0,salary:0};setData(x=>[n,...x]);setModal(null)}
return <AppShell title="Colaboradores" subtitle="Cadastro, dados profissionais e jornada de cada pessoa." actions={<><button className="secondary" onClick={()=>setModal('import')}>Importar</button><button onClick={()=>setModal('new')}>+ Novo colaborador</button></>}>
<div className="kpi-grid four"><div className="metric"><span>Total</span><strong>127</strong><small>+5 este mês</small></div><div className="metric"><span>Ativos</span><strong>{data.filter(x=>x.status!=='Inativo').length}</strong><small>96% do quadro</small></div><div className="metric"><span>Férias</span><strong>{data.filter(x=>x.status==='Férias').length+7}</strong><small>retornos próximos</small></div><div className="metric"><span>Novas admissões</span><strong>6</strong><small>nos últimos 30 dias</small></div></div>
<div className="toolbar"><div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por nome, cargo ou e-mail..."/></div><select value={dept} onChange={e=>setDept(e.target.value)}><option>Todos</option>{[...new Set(data.map(x=>x.department))].map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>Todos</option><option>Ativo</option><option>Férias</option><option>Inativo</option></select><button className="secondary" onClick={()=>setModal('filter')}>☷ Filtros avançados</button><div className="view-switch"><button className={view==='table'?'selected':''} onClick={()=>setView('table')}>☷</button><button className={view==='cards'?'selected':''} onClick={()=>setView('cards')}>▦</button></div></div>
<div className="table-meta"><span><b>{filtered.length}</b> colaboradores encontrados</span><button className="link-btn">Exportar CSV ↓</button></div>
{view==='table'?<div className="section-card table-wrap"><table><thead><tr><th>Colaborador</th><th>Cargo / setor</th><th>Gestor</th><th>Status</th><th>Desempenho</th><th>PDI</th><th></th></tr></thead><tbody>{filtered.map(e=><tr key={e.id}><td><Link className="person-cell" to={`/people/employees/${e.id}`}><Avatar initials={e.initials}/><span><b>{e.name}</b><small>{e.email}</small></span></Link></td><td><b>{e.role}</b><small>{e.department}</small></td><td>{e.manager}</td><td><Badge tone={tone(e.status)}>{e.status}</Badge></td><td><strong>{e.performance?e.performance.toFixed(1):'—'}</strong><small>/ 5,0</small></td><td><div className="mini-progress"><Progress value={e.pdi}/><span>{e.pdi}%</span></div></td><td><Link className="more" to={`/people/employees/${e.id}`}>•••</Link></td></tr>)}</tbody></table></div>:<div className="people-cards">{filtered.map(e=><Link className="person-card" key={e.id} to={`/people/employees/${e.id}`}><div className="person-card-top"><Avatar initials={e.initials} large/><Badge tone={tone(e.status)}>{e.status}</Badge></div><h3>{e.name}</h3><p>{e.role}</p><small>{e.department} · {e.location}</small><div className="card-stats"><span>Desempenho <b>{e.performance.toFixed(1)}</b></span><span>PDI <b>{e.pdi}%</b></span></div><Progress value={e.pdi}/></Link>)}</div>}
{modal==='new'&&<Modal title="Novo colaborador" onClose={()=>setModal(null)} footer={<><button className="secondary" onClick={()=>setModal(null)}>Cancelar</button><button onClick={add}>Salvar colaborador</button></>}><div className="wizard-progress"><b>1</b><span>Dados pessoais</span><i/><b>2</b><span>Profissional</span><i/><b>3</b><span>Contrato</span><i/><b>4</b><span>Benefícios</span><i/><b>5</b><span>Documentos</span></div><div className="form-grid"><label>Nome completo<input defaultValue="Novo Colaborador"/></label><label>E-mail<input defaultValue="novo.colaborador@empresa.com"/></label><label>CPF<input placeholder="000.000.000-00"/></label><label>Data de nascimento<input type="date"/></label><label>Telefone<input placeholder="(51) 99999-9999"/></label><label>Localidade<select><option>Porto Alegre</option><option>São Paulo</option><option>Curitiba</option></select></label></div></Modal>}
{modal==='filter'&&<Modal title="Filtros avançados" onClose={()=>setModal(null)} footer={<><button className="secondary" onClick={()=>setModal(null)}>Limpar</button><button onClick={()=>setModal(null)}>Aplicar filtros</button></>}><div className="form-grid"><label>Faixa de desempenho<select><option>Qualquer</option><option>Acima de 4,5</option><option>Abaixo de 4,0</option></select></label><label>Tempo de casa<select><option>Qualquer</option><option>Até 1 ano</option><option>Mais de 3 anos</option></select></label><label>PDI<select><option>Qualquer</option><option>Abaixo de 50%</option><option>Acima de 80%</option></select></label><label>Contrato<select><option>Todos</option><option>CLT</option><option>PJ</option></select></label></div></Modal>}
{modal==='import'&&<Modal title="Importar colaboradores" onClose={()=>setModal(null)} footer={<><button className="secondary" onClick={()=>setModal(null)}>Cancelar</button><button onClick={()=>setModal(null)}>Importar arquivo</button></>}><div className="dropzone"><strong>Arraste o CSV aqui</strong><span>ou clique para selecionar um arquivo</span><small>Formato aceito: .csv · limite 10 MB</small></div><p className="muted">A importação atualiza registros pelo e-mail e mostra um resumo antes de concluir.</p></Modal>}
</AppShell>}
